local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = '[S]earch [F]iles' })
vim.keymap.set('n', '<C-p>', builtin.git_files, { desc = '[P]roject files' })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set( "n", "<leader>fb", ":Telescope file_browser<CR>" )
